nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/api/':
                allow_origin: ['*']
                allow_headers: ['X-AUTH-TOKEN', 'Content-Type']
                allow_methods: ['POST', 'PUT', 'PATH', 'GET', 'DELETE']
                max_age: 3600
            '^/login_check':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth', 'content-type','accept']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/userapp_create':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth', 'content-type','accept']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']